import pandas as pd
df = pd.read_csv("iris.csv")
print("First 8 Rows:")
print(df.head(8))
print("\nColumn Names:")
print(df.columns)
print("\nMissing Values Before Handling:")
print(df.isnull().sum())
df.fillna(df.mean(numeric_only=True), inplace=True)
df.dropna(inplace=True)
print("\nMissing Values After Handling:")
print(df.isnull().sum())
print("\nGrouped Data (Species Count):")
print(df.groupby("Species").size())
print("\nSepal Length Statistics:")
print("Mean:", df["SepalLengthCm"].mean())
print("Minimum:", df["SepalLengthCm"].min())
print("Maximum:", df["SepalLengthCm"].max())